---
title: "Project Code Musk Oxen"
output: pdf_document
author: "Jack Nowacek"
date: "2023-10-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

## Packages

```{r packages}
library(tidyverse)
library(readxl)
library(grid)
library(gridExtra)
```

## Data Introduction

```{r Data Formatting}
data <- read_excel("~/Documents/Copenhagen/Polar_Bio/MuskOxenData.xlsx")
data <- data |>
  select(!Remarks) |>
  na.omit()
```

## EDA

```{r exploratory data analysis}
p1 <- ggplot(data = data, aes(x = Year, y = MeanDensity)) +
  geom_point() +
  geom_path() +
  geom_abline() +
  theme_minimal()

p2 <- ggplot(data = data, aes(x = Year, y = WinterTemp)) +
  geom_point() +
  geom_path() +
  geom_abline() +
  theme_minimal()

p3 <- ggplot(data = data, aes(x = Year, y = SpringSnow)) +
  geom_point() +
  geom_path() +
  geom_abline() +
  theme_minimal()

p4 <- ggplot(data = data, aes(x = Year, y = CalfPercentage)) +
  geom_point() +
  geom_path() +
  geom_abline() +
  theme_minimal()

# p1
# p2
# p3
# p4

grid.arrange(p1, p2, p3, p4, nrow = 2)

# data |>
#   ggplot(aes(x = Year, group = 1)) +
#   geom_path(aes(y = CalfPercentage)) +
#   geom_point(aes(y = CalfPercentage)) +
#   geom_path(aes(y = MeanDensity)) +
#   geom_point(aes(y = MeanDensity)) +
#   theme_linedraw() 
  
```

```{r linear regressions}
density_reg <- lm(CalfPercentage ~ MeanDensity, data = data)
density_summ <- summary(density_reg)
density_summ$r.squared

temp_reg <- lm(CalfPercentage ~ WinterTemp, data = data)
temp_summ <- summary(temp_reg)
temp_summ$r.squared

snow_reg <- lm(CalfPercentage ~ SpringSnow, data = data)
snow_summ <- summary(snow_reg)
snow_summ$r.squared

all_reg <- lm(CalfPercentage ~ MeanDensity + WinterTemp + SpringSnow, data = data)
all_summ <- summary(all_reg)
all_summ$r.squared

density_to_springsnow <- lm(MeanDensity ~ SpringSnow, data = data)
summary <- summary(density_to_springsnow)
summary$r.squared
```

```{r outlier query}
g1 <- data |>
  ggplot(aes(CalfPercentage)) +
  geom_boxplot()

g2 <- data |>
  ggplot(aes(WinterTemp)) +
  geom_boxplot()

g3 <- data |>
  ggplot(aes(SpringSnow)) +
  geom_boxplot()

g4 <- data |>
  ggplot(aes(MeanDensity)) +
  geom_boxplot()

grid.arrange(g1, g2, g3, g4, nrow = 2)
```

```{r dropped outlier data}
# no_outliers_data <- data |>
#   subset(id = c(5, 10, 11))

data_no_out <- data[-c(5,10,11),]

density_reg2 <- lm(CalfPercentage ~ MeanDensity, data = data_no_out)
density_summ2 <- summary(density_reg2)
density_summ2$r.squared

temp_reg2 <- lm(CalfPercentage ~ WinterTemp, data = data_no_out)
temp_summ2 <- summary(temp_reg2)
temp_summ2$r.squared

snow_reg2 <- lm(CalfPercentage ~ SpringSnow, data = data_no_out)
snow_summ2 <- summary(snow_reg2)
snow_summ2$r.squared

all_reg2 <- lm(CalfPercentage ~ MeanDensity + WinterTemp + SpringSnow, data = data_no_out)
all_summ2 <- summary(all_reg2)
all_summ2$r.squared
```

```{r winter_temp predicts spring snow of next year}
snowy_data <- data |>
  select(!c("Year", "MeanDensity", "CalfPercentage")) |>
  mutate(SpringSnow=lead(SpringSnow)) |>
  slice(1:n()-1)

snowy_reg <- lm(SpringSnow ~ WinterTemp, data = snowy_data)
snowy_summ <- summary(snowy_reg)
snowy_summ$r.squared
```

Failed, no correlation between previous winter temperature and the snow cover of the next year.

EOF